export declare const stylings: {
    base: string;
    spacing: string;
    borderRadius: string;
    boxShadow: string;
    breakpoints: {
        mini: string;
        tiny: string;
        small: string;
        medium: string;
        large: string;
        big: string;
        huge: string;
    };
    typography: {
        font: string;
        text: string;
        title: string;
    };
    headerHeight: string;
    transitionDuration: string;
    colors: {
        primaryActive: string;
        primaryAltActive: string;
        primaryLightActive: string;
        primaryDarkActive: string;
        primaryGreyDarkActive: string;
        primaryGreyActive: string;
        primaryGreyLightActive: string;
        infoActive: string;
        successActive: string;
        dangerActive: string;
        warningActive: string;
        primary: string;
        primaryAlt: string;
        primaryLight: string;
        primaryDark: string;
        primaryGreyDark: string;
        primaryGrey: string;
        primaryGreyLight: string;
        info: string;
        success: string;
        danger: string;
        warning: string;
        primaryBackground: string;
        primaryAltBackground: string;
        primaryLightBackground: string;
        primaryDarkBackground: string;
        primaryGreyDarkBackground: string;
        primaryGreyBackground: string;
        primaryGreyLightBackground: string;
        infoBackground: string;
        successBackground: string;
        dangerBackground: string;
        warningBackground: string;
    };
};
