export declare const stylings: {
    base: string;
    spacing: string;
    borderRadius: string;
    boxShadow: string;
    breakpoints: {
        mini: string;
        tiny: string;
        small: string;
        medium: string;
        large: string;
        big: string;
        huge: string;
    };
    typography: {
        font: string;
        text: string;
        title: string;
    };
    headerHeight: string;
    transitionDuration: string;
    colors: {
        primaryActive: string;
        secondaryActive: string;
        primaryAltActive: string;
        primaryDarkActive: string;
        infoActive: string;
        successActive: string;
        dangerActive: string;
        warningActive: string;
        primary: string;
        secondary: string;
        primaryAlt: string;
        primaryDark: string;
        primaryGreyDarker: string;
        primaryGreyDark: string;
        primaryGrey: string;
        primaryGreyLight: string;
        primaryGreyLighter: string;
        info: string;
        success: string;
        danger: string;
        warning: string;
        primaryBackground: string;
        secondaryBackground: string;
        primaryAltBackground: string;
        primaryDarkBackground: string;
        infoBackground: string;
        successBackground: string;
        dangerBackground: string;
        warningBackground: string;
    };
};
